#
# Copyright (C) 2025 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: pr-check

permissions:
  contents: read

on: [pull_request]

jobs:
  build:
    name: Build / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-2022"
          - os: "macos-14"
          - os: "ubuntu-24.04"
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Execute pnpm
        run: pnpm install --frozen-lockfile

      - name: Run typecheck
        run: pnpm typecheck

        # skip formatter on windows
      - name: Run formatter
        if: ${{ matrix.os=='ubuntu-24.04' || matrix.os=='macos-14' }}
        run: pnpm format:check

      - name: Run linter
        run: pnpm lint:check

      - name: Run tests
        run: pnpm test

      - name: Run build
        run: pnpm build
        timeout-minutes: 40